---
title: Brick and Monitor
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: brian@brickandmonitor.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl:
url: http://localhost:4000
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown

sass:
  # style: compressed
  #sass_dir: _assets/css/_sass

gems:
  - jekyll-assets

assets:
  compress:
    css: true
    js: true

  autowrite: true
  cache: false
  #cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  #digest: true

  assets:
    - "*.png"
    - "bundle.css"

  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
